import Nav from '@/components/Nav';
import './globals.css';
import { Montserrat, Shrikhand } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
  weight: ['300', '600']
});

const shrikhand = Shrikhand({
  subsets: ['latin'],
  variable: '--font-shrik',
  weight: '400'
});

export const metadata = {
  title: "Tara MacKinnon's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${shrikhand.variable} font-mont`}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
